version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: razor_app
    ports:
      - "5000:80"  # ASP.NET domyœlnie dzia³a na porcie 80 w kontenerze
    restart: unless-stopped
